package dao;

import java.util.List;
import model.PersonalEducationInfo;
import model.PersonalEducationInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PersonalEducationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    long countByExample(PersonalEducationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    int deleteByExample(PersonalEducationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    int insert(PersonalEducationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    int insertSelective(PersonalEducationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    List<PersonalEducationInfo> selectByExampleWithRowbounds(PersonalEducationInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    List<PersonalEducationInfo> selectByExample(PersonalEducationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    PersonalEducationInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") PersonalEducationInfo record, @Param("example") PersonalEducationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    int updateByExample(@Param("record") PersonalEducationInfo record, @Param("example") PersonalEducationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    int updateByPrimaryKeySelective(PersonalEducationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_education_info
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    int updateByPrimaryKey(PersonalEducationInfo record);
}