package model;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.user_name
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.job_position
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private String jobPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.status
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.entry_time
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private Date entryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.dimission_time
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private Date dimissionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.promotion_time
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private Date promotionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.salary
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private Integer salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.department
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_id
     *
     * @return the value of employee.employee_id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_id
     *
     * @param employeeId the value for employee.employee_id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.user_name
     *
     * @return the value of employee.user_name
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.user_name
     *
     * @param userName the value for employee.user_name
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.job_position
     *
     * @return the value of employee.job_position
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public String getJobPosition() {
        return jobPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.job_position
     *
     * @param jobPosition the value for employee.job_position
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setJobPosition(String jobPosition) {
        this.jobPosition = jobPosition == null ? null : jobPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.status
     *
     * @return the value of employee.status
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.status
     *
     * @param status the value for employee.status
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.entry_time
     *
     * @return the value of employee.entry_time
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.entry_time
     *
     * @param entryTime the value for employee.entry_time
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.dimission_time
     *
     * @return the value of employee.dimission_time
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public Date getDimissionTime() {
        return dimissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.dimission_time
     *
     * @param dimissionTime the value for employee.dimission_time
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setDimissionTime(Date dimissionTime) {
        this.dimissionTime = dimissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.promotion_time
     *
     * @return the value of employee.promotion_time
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public Date getPromotionTime() {
        return promotionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.promotion_time
     *
     * @param promotionTime the value for employee.promotion_time
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setPromotionTime(Date promotionTime) {
        this.promotionTime = promotionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.salary
     *
     * @return the value of employee.salary
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.salary
     *
     * @param salary the value for employee.salary
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.department
     *
     * @return the value of employee.department
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.department
     *
     * @param department the value for employee.department
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }
}