package model;

public class PersonalEducationInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_education_info.id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_education_info.user_name
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_education_info.personal_id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private String personalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_education_info.education_background
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    private String educationBackground;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_education_info.id
     *
     * @return the value of personal_education_info.id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_education_info.id
     *
     * @param id the value for personal_education_info.id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_education_info.user_name
     *
     * @return the value of personal_education_info.user_name
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_education_info.user_name
     *
     * @param userName the value for personal_education_info.user_name
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_education_info.personal_id
     *
     * @return the value of personal_education_info.personal_id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public String getPersonalId() {
        return personalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_education_info.personal_id
     *
     * @param personalId the value for personal_education_info.personal_id
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setPersonalId(String personalId) {
        this.personalId = personalId == null ? null : personalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_education_info.education_background
     *
     * @return the value of personal_education_info.education_background
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public String getEducationBackground() {
        return educationBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_education_info.education_background
     *
     * @param educationBackground the value for personal_education_info.education_background
     *
     * @mbg.generated Sun Jul 01 15:30:17 CST 2018
     */
    public void setEducationBackground(String educationBackground) {
        this.educationBackground = educationBackground == null ? null : educationBackground.trim();
    }
}